export const permissionsArray = [
  "emp_search_and_view",
  "emp_manage_files",
  "emp_add",
  "emp_update",
  "emp_delete",
  "emp_view_specific",

  "job_title_search_and_view",
  "job_title_manage_files",
  "job_title_add",
  "job_title_update",
  "job_title_delete",
  "job_title_view_specific",
  "job_title_category_search_and_view",
  "job_title_category_manage_files",
  "job_title_category_add",
  "job_title_category_update",
  "job_title_category_delete",

  "department_search_and_view",

  "department_manage_files",
  "department_add",
  "department_update",
  "department_delete",
  "department_view_specific",

  "permission_search_and_view",
  "permission_add",
  "permission_update",
  "permission_delete",

  "electronic_transaction_search_and_view",
  "electronic_transaction_manage_files",
  "electronic_transaction_add",
  "electronic_transaction_update",
  "electronic_transaction_delete",

  "task_search_and_view",
  "task_manage_files",
  "task_add",
  "task_update",
  "task_delete",
];
